### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by EF6667** [SuperKael/Gadget-Core#11]
Could you tell me how to use this mod?

**Comment by SuperKael** [comment]
I apologize, I do not regularly check GitHub issues, and after six months I imagine you long since figured it out yourself, or moved on. That said, using GadgetCore is as simple as downloading the latest installer file from the [Releases page](https://github.com/SuperKael/Gadget-Core/releases), and running it. The installer will attempt to auto-detect your Roguelands installation, but if it fails, you can direct it manually. Once GadgetCore is installed, a new Mod Menu button will appear on the game's title screen, and from the Mod Menu you can open the Mod Browser. There, you can browse other mods that you wish to download and install.
